## https://datascienceschool.net/view-notebook/6927b0906f884a67b0da9310d3a581ee/
## https://blog.theeluwin.kr/post/146591096133/%ED%95%9C%EA%B5%AD%EC%96%B4-word2vec
## https://ratsgo.github.io/natural%20language%20processing/2017/03/08/word2vec/
## https://wikidocs.net/22660
## https://www.depends-on-the-definition.com/guide-to-word-vectors-with-gensim-and-keras/

In [3]:
import gensim
import tensorflow as tf
import pandas as pd
import numpy as np
keras = tf.keras

In [4]:
df = pd.read_csv('train_intent.csv')

In [5]:
df.size

7836

In [20]:
tmp = dict(df)
print(type(tmp['question'][0]))

<class 'str'>


In [25]:
dataset = tf.data.Dataset.from_tensor_slices(dict(df))

In [31]:
for i in dataset.take(5):
    print(tf.strings.unicode_decode(i['question'],
                          input_encoding='UTF-8'), 
          tf.strings.unicode_decode(i['intent'],
                          input_encoding='UTF-8'))

tf.Tensor([50640 54589 54616 51060    32 50864 49328    32 46308 47140 51480], shape=(11,), dtype=int32) tf.Tensor([51020 50501], shape=(2,), dtype=int32)
tf.Tensor([50980 54616    32 50864 49328    32 46308 47140 51480], shape=(9,), dtype=int32) tf.Tensor([51020 50501], shape=(2,), dtype=int32)
tf.Tensor([50980 54616 51032    32 50864 49328    32 46308 47140 51452 46972], shape=(11,), dtype=int32) tf.Tensor([51020 50501], shape=(2,), dtype=int32)
tf.Tensor([50864 49328    32 45432 47000    32 46308 47140 51480], shape=(9,), dtype=int32) tf.Tensor([51020 50501], shape=(2,), dtype=int32)
tf.Tensor([50640 54589 54616 51060 51032    32 50864 49328    32 46308 47140 51480], shape=(12,), dtype=int32) tf.Tensor([51020 50501], shape=(2,), dtype=int32)


In [ ]:
pretrained_word2vec='/home/dan/prj/nlp/deep_chatbot/ko/ko.bin'

In [ ]:
model = gensim.models.Word2Vec.load(pretrained_word2vec)

In [ ]:
model.most_similar(positive=["디자인"], topn=100)

In [ ]:
model.wv.word_vec(['강아지', '고양이'])

In [ ]:
model.wv.get_keras_embedding

In [ ]:
model.wv.most_similar("강아지")

In [ ]:
vec = model.wv(['강아지', '개', '고양이'])

In [ ]:
model.wv.word_vec(['강아지'])

In [ ]:
dog_vec = model.wv.word_vec('개')
cat = model.wv.word_vec('고양이')

In [ ]:


np.square  dog_vec - pup_vec

In [ ]:
import numpy as np
print(np.linalg.norm(pup_vec-dog_vec))

In [ ]:
print(np.linalg.norm(cat-dog_vec))

In [ ]:
print(np.linalg.norm(pup_vec-cat))

# Use it with keras

### https://www.depends-on-the-definition.com/guide-to-word-vectors-with-gensim-and-keras/

In [6]:
import gensim
Word2Vec = gensim.models.Word2Vec
pretrained_word2vec='/home/dan/prj/nlp/deep_chatbot/ko/ko.bin'

In [7]:
model = Word2Vec.load(pretrained_word2vec)

In [8]:
word_vectors = model.wv

In [10]:
len(word_vectors.vocab)

30185

In [ ]:
word_vectors.word_vec('정어리')

In [4]:
import numpy as np
import tensorflow as tf
keras = tf.keras
import intent_data

In [5]:
intent_data.make_intent_data()

0  :  ('음악', 359)
1  :  ('번역', 286)
2  :  ('뉴스', 271)
3  :  ('명언', 316)
4  :  ('달력', 307)
5  :  ('먼지', 313)
6  :  ('인물', 303)
7  :  ('시간', 344)
8  :  ('위키', 327)
9  :  ('이슈', 376)
10  :  ('날씨', 372)
11  :  ('맛집', 344)


In [ ]:
MAX_NB_WORDS = len(word_vectors.vocab)
MAX_SEQUENCE_LENGTH = 200

In [ ]:
from keras.preprocessing.sequence import pad_sequences

word_index = {t[0]: i+1 for i,t in enumerate(vocab.most_common(MAX_NB_WORDS))}
sequences = [[word_index.get(t, 0) for t in comment]
             for comment in comments[:len(list_sentences_train)]]
test_sequences = [[word_index.get(t, 0)  for t in comment] 
                  for comment in comments[len(list_sentences_train):]]

# pad
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, 
                     padding="pre", truncating="post")
list_classes = ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]
y = train_df[list_classes].values
print('Shape of data tensor:', data.shape)
print('Shape of label tensor:', y.shape)

test_data = pad_sequences(test_sequences, maxlen=MAX_SEQUENCE_LENGTH, padding="pre",
                          truncating="post")
print('Shape of test_data tensor:', test_data.shape)

In [ ]:
WV_DIM = 100
nb_words = min(MAX_NB_WORDS, len(word_vectors.vocab))
# we initialize the matrix with random numbers
wv_matrix = (np.random.rand(nb_words, WV_DIM) - 0.5) / 5.0
for word, i in word_index.items():
    if i >= MAX_NB_WORDS:
        continue
    try:
        embedding_vector = word_vectors[word]
        # words not found in embedding index will be all-zeros.
        wv_matrix[i] = embedding_vector
    except:
        pass        

In [ ]:
wv_layer = Embedding(nb_words,
                     WV_DIM,
                     mask_zero=False,
                     weights=[wv_matrix],
                     input_length=MAX_SEQUENCE_LENGTH,
                     trainable=False)