# Numpy 기초

파이썬 데이터 분석의 3대 라이브러리: 
* Numpy : 배열, 행열을 다룸
* Pandas : 엑셀와 같은 데이터프레임을 다룸
* Matplotlib : 시각화

https://numpy.org/


In [0]:
# numpy 라이브러리 임포트(불러오기)

import numpy as np

In [0]:
# 2. Array 정의 및 사용하기
# 리스트와 어레이(배열)의 차이

data1 = [1,2,3,4,5]
data2 = [1,2,3,3.5,4]

In [0]:
# Numpy를 이용하여 array 정의하기
# 2-1. 위에서 만든 python list를 이용

arry1 = np.array(data1)

print(data1)
print(arry1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [0]:
# array의 형태(크기) 확인

arry1.shape

(5,)

In [0]:
a = np.array([[1,2,3], [1,2,3]])
a.shape

(2, 3)

In [0]:
b = np.array([[1,2,3], [1,2,3], [1,2,3]])
b.shape

(3, 3)

In [0]:
c = np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
c.shape

(2, 3, 3)

In [0]:
# 2-2. 바로 python list를 넣어 줌으로써 만들기

arry2 = np.array([1,3,5,7])
arry2.shape

(4,)

In [18]:
# array의 자료형을 확인

arry2.dtype

dtype('int64')

In [23]:
arry3 = np.array(data2)
arry3

array([1. , 2. , 3. , 3.5, 4. ])

In [21]:
arry3.dtype

dtype('float64')

In [22]:
arry3.shape

(5,)

In [24]:
arry3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arry3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
arry3.shape

(4, 3)

#### numpy shape
<pre>
numpy에서는 해당 array의 크기를 알 수 있다.
shape 을 확인함으로써 몇 개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.
위에서 arr1.shape의 결과는 (5,)으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다.
arr4.shape의 결과는 (4,3)으로써, 2차원의 데이터이며 4*3 크기를 갖고 있는 array이다.
</pre>

#### numpy 자료형
<pre>
arr1이나 arr2는 int라는 자료형을 갖는 것에 반해 arr3는 float64라는 자료형을 갖는다.
이는 arr3 내부 데이터를 살펴보면 3.5라는 실수형 데이터를 갖기 때문임을 알 수 있다.
numpy에서 사용되는 자료형은 아래와 같다.
(자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미한다.)

* 부호가 있는 정수 int(8, 16, 32, 64)
* 부호가 없는 정수 uint(8, 16, 32, 54)
* 실수 float(16, 32, 64, 128)
* 복소수 complex(64, 128, 256)
* 불리언 bool
* 문자열 string
* 파이썬 오브젝트 object
* 유니코드 unicode_
</pre>

#### 2-1. np.zeros(), np.ones(), np.arange() 함수
<pre>
numpy에서 array를 정의할 때 사용되는 함수들이다.
아래 실습을 통해 각각이 어떻게 다른지 살펴본다.
</pre>



In [0]:
# np.zeros() 함수는 인자로 받는 크기만큼, 모든 요소가 0인 array를 만든다.

In [27]:
arry5 = np.zeros(10)
arry5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
arry6 = np.zeros((2,4))
arry6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
arry7 = np.zeros((3,3,3))
arry7

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [0]:
# np.ones() 함수는 인자로 받는 크기만큼, 모든 요소가 1인 array를 만든다.

In [32]:
arry8 = np.ones(9)
arry8

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
arry9 = np.ones((4,3))
arry9                

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
# np.arange() 함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만든다.
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가진다.

In [34]:
arry10 = np.arange(10)
arry10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3.Array 연산
<pre>
기본적으로 numpy 에서 연산을 할 때는 크기가 서로 동일한 array 끼리 연산이 진행된다.
이 때 같은 위치에 있는 요소들 끼리 연산이 진행된다.

In [40]:
arry1 = np.array([[1,2,3],[4,5,6]])
arry2 = np.array([[10,11,12],[13,14,15]])

print(arry1)
print(arry2)

[[1 2 3]
 [4 5 6]]
[[10 11 12]
 [13 14 15]]


In [41]:
# 3-1. array 덧셈
arry3 = arry1 + arry2
arry3

array([[11, 13, 15],
       [17, 19, 21]])

In [42]:
# 3-2. array 뺄셈
arry4 = arry1 - arry2
arry4

array([[-9, -9, -9],
       [-9, -9, -9]])

In [43]:
# 3-3. array 곱셈
# 주의하자.
# 행렬의 곱처럼 곱셈이 진행되는 것이 아니라 각 요소별로 곱셈이 진행된다.

arry5 = arry1 * arry2
arry5

array([[10, 22, 36],
       [52, 70, 90]])

In [44]:
# 3-4. array 나눗셈

arry6 = arry1 / arry2
arry6

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [0]:
# 3-5.array의 브로드 캐스트
# 위에서는 array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만,
# numpy에서는 브로드캐스트라는 기능을 제공한다.
# 브로드캐스트란, 서로 크기가 다른 array가 연산이 가능하게끔 하는 것이다.

In [49]:
arry3 = np.array([10,11,12])
arry4 = np.array([1,2])
print(arry1)
print(arry3)
print(arry4)

[[1 2 3]
 [4 5 6]]
[10 11 12]
[1 2]


In [47]:
arry7 = arry1 + arry3
arry7

array([[11, 13, 15],
       [14, 16, 18]])

In [50]:
arry8 = arry1 + arry4
arry8

ValueError: ignored

In [51]:
arry9 = arry1 * arry3
arry9

array([[10, 22, 36],
       [40, 55, 72]])

In [54]:
# 위와 같이 서로 크기가 다른 arr1과 arr3의 연산이 가능하다.
# 연산 결과를 살펴보면 arr3이 [10,11,12] 에서 [[10,11,12],[10,11,12]]로 확장되어
# 계산되었음을 알 수 있다.
# 동일한 방식으로 하나의 array에 스칼라 연산도 가능하다.

arry1*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [55]:
# 요소에 대해 제곱처리
arry1**3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [0]:
# 4. Array 인덱싱
# numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.
# 이 때, python에서와 같이 1번째로 시작하는 것이 아니라 0번째로 시작 하는 것.
# 주의!

In [57]:
arry1 = np.arange(10)
arry1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# 0번째 요소
arry1[0]

0

In [61]:
# 3번째 요소
arry1[3]

3

In [60]:
# 3번째 요소부터 8번째 요소
arry1[3:9]

array([3, 4, 5, 6, 7, 8])

In [62]:
# 물론 1차원이 아닌 그 이상의 차원에서도 인덱싱이 가능하다.
arry2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arry2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
# 2차원의 array에서 인덱싱을 하기 위해서는 2개의 인자를 입력해야 한다.
arry2[0,0]

1

In [69]:
arry2[1,2]

6

In [71]:
arry2[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
# 2행의 모든 요소 꺼내기
arry2[1,:]

array([4, 5, 6])

In [77]:
# 2행의 3번째 요소 꺼내기
arry2[1,2]

6

In [82]:
arry2[1,2:]  #?????

array([6])

In [78]:
# 모든 열의 3번째 요소 꺼내기
arry2[:,2]

array([ 3,  6,  9, 12])

In [0]:
# 5. Array boolean 인덱싱(마스크)
# 위에서 이용한 다차원의 인덱싱을 응용하여 boolean 인덱싱을 할 수 있다.
# 해당 기능은 주로 마스크라고 이야기하는데,
# boolean 인덱싱을 통해 만들어 낸 array를 통해
# 우리가 원하는 행 또는 열의 값만 뽑아낼 수 있다.
# 즉 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.

In [0]:
names = np.array(['lee', 'park', 'kim', 'john', 'lee', 
                  'john', 'park', 'lee'])


In [84]:
names.shape

(8,)

In [122]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고,
# 표준 편차가 1인 가우시안 정규분포를 따르는 난수를 발생시키는 함수이다.
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재한다.

data = np.random.randn(8,4)
data               

array([[ 1.22239556,  0.15006993,  0.60008807,  0.28320572],
       [-0.07190241,  1.05256011, -0.34644138, -0.06873844],
       [ 0.83737338, -2.02741352,  1.42112795,  2.2288851 ],
       [ 0.18476796, -0.29600158,  0.2711616 ,  1.32144517],
       [ 0.74469614, -0.07415154,  0.2328654 ,  0.55694902],
       [-0.29694427, -0.5661868 , -1.18162785,  0.23234294],
       [-1.57823256, -2.93452617,  1.45164179,  0.62955218],
       [ 0.31284692, -0.55787939,  1.19596793, -2.1549908 ]])

In [86]:
data.shape

(8, 4)

In [0]:
# 위와 같은 names와 data라는 array가 있다.
# 이 때, names의 각 요소가 data의 각 행과 연결된다고 가정해보자.
# 그리고 이 때, names가 lee인 행의 data만 보고 싶을 때 다음과 같이 마스크를 사용.

In [87]:
# 요소가 lee인 항목에 대한 mask 생성

names_lee_mask = (names == 'lee')
names_lee_mask

array([ True, False, False, False,  True, False, False,  True])

In [88]:
data[names_lee_mask]

array([[ 1.12215165, -0.60454772, -1.47030196,  0.22494869],
       [ 0.40652958,  1.21103353, -0.33494558, -0.30937094],
       [-0.24629776,  0.88257538,  0.99717263,  1.05253305]])

In [0]:
# 위의 결과를 보면, 요소가 lee인 것은 0번째, 4번째, 7번째 이므로
# data에서 0,4,7행의 모든 요소를 꺼내와야 한다.
# 이를 위해 요소가 lee인 것에 대한 boolean 값을 가지는 mask를 만들었고,
# 마스크를 인덱싱에 응용하여 data의 0,4,7행을 꺼냈다.

In [95]:
# 요소가 kim인 행의 데이터만 꺼내기
names_kim_mask = (names == 'kim')
data[names_kim_mask,:]

array([[-1.01106634, -1.08445103, -2.00819005,  1.06082109]])

In [96]:
# 요소가 kim인 행을 제외한 데이터만 꺼내기
names_kim_mask = (names != 'kim')
data[names_kim_mask,:]

array([[ 1.12215165, -0.60454772, -1.47030196,  0.22494869],
       [-0.70310877,  0.88951944,  0.04764265,  0.61262128],
       [ 0.42853117,  1.4108094 , -0.87829884,  0.15207262],
       [ 0.40652958,  1.21103353, -0.33494558, -0.30937094],
       [-0.3498443 ,  1.38144165, -0.32043544,  0.24518134],
       [ 0.51472253,  0.27568015, -0.59427129,  0.82558006],
       [-0.24629776,  0.88257538,  0.99717263,  1.05253305]])

In [107]:
# 논리 연산을 응용하여, 요소가 kim 또는 park 인 행의 데이터만 꺼내기
name_or = (names=='kim')|(names=='park')
data[name_or]

array([[-0.70310877,  0.88951944,  0.04764265,  0.61262128],
       [-1.01106634, -1.08445103, -2.00819005,  1.06082109],
       [ 0.51472253,  0.27568015, -0.59427129,  0.82558006]])

In [111]:
name_and = (names=='kim')+(names=='park')
data[name_and]

array([[-0.70310877,  0.88951944,  0.04764265,  0.61262128],
       [-1.01106634, -1.08445103, -2.00819005,  1.06082109],
       [ 0.51472253,  0.27568015, -0.59427129,  0.82558006]])

In [0]:
# 물론 data array 자체적으로도 마스크를 만들고, 이를 응용하여 인덱싱이 가능하다.
# data array에서 0번째 열의 값이 0보다 작은 행을 구해보자.

In [123]:
# 먼저 마스크를 만든다.
# data array에서 0번째 열이 0보다 작은 요소의 boolean 값은 다음과 같다.
print(data)
data[:,0]<0

[[ 1.22239556  0.15006993  0.60008807  0.28320572]
 [-0.07190241  1.05256011 -0.34644138 -0.06873844]
 [ 0.83737338 -2.02741352  1.42112795  2.2288851 ]
 [ 0.18476796 -0.29600158  0.2711616   1.32144517]
 [ 0.74469614 -0.07415154  0.2328654   0.55694902]
 [-0.29694427 -0.5661868  -1.18162785  0.23234294]
 [-1.57823256 -2.93452617  1.45164179  0.62955218]
 [ 0.31284692 -0.55787939  1.19596793 -2.1549908 ]]


array([False,  True, False, False, False,  True,  True, False])

In [124]:
# 위에서 만든 마스크를 이용하여 0번째 열의 값이 0보다 작은 행을 구한다.
data_mask = data[:,0]<0
data[data_mask]

array([[-0.07190241,  1.05256011, -0.34644138, -0.06873844],
       [-0.29694427, -0.5661868 , -1.18162785,  0.23234294],
       [-1.57823256, -2.93452617,  1.45164179,  0.62955218]])

In [0]:
# 이를 통해 특정 위치에만 우리가 원하는 값을 대입할 수 있다.
# 위에서 얻은, 0번째 열의 값이 0보다 작은 행의
# 2,3번째 열의 값에 0을 대입해보자.

In [131]:
# 0번째 열의 값이 0보다 작은 행의 2,3 번째 열 값
data[data_mask, 1:3] = 0
data

array([[ 1.22239556,  0.15006993,  0.60008807,  0.28320572],
       [-0.07190241,  0.        ,  0.        , -0.06873844],
       [ 0.83737338, -2.02741352,  1.42112795,  2.2288851 ],
       [ 0.18476796, -0.29600158,  0.2711616 ,  1.32144517],
       [ 0.74469614, -0.07415154,  0.2328654 ,  0.55694902],
       [-0.29694427,  0.        ,  0.        ,  0.23234294],
       [-1.57823256,  0.        ,  0.        ,  0.62955218],
       [ 0.31284692, -0.55787939,  1.19596793, -2.1549908 ]])

In [0]:
# 6. Numpy 함수
# numpy에서는 array에 적용되는 다양한 함수가 있다.

In [132]:
# 6-1. 하나의 array에 적용되는 함수
arr1 = np.random.randn(5,3)
arr1

array([[-0.54386673, -0.5009612 ,  1.31427785],
       [-1.76242647,  0.78498683, -0.57578388],
       [-0.62868444, -0.0438871 ,  1.65200415],
       [ 2.18918111, -1.62267317,  0.09498678],
       [ 0.5757371 , -0.10993565, -0.07281788]])

In [133]:
# 각 성분의 절대값 계산하기
np.abs(arr1)

array([[0.54386673, 0.5009612 , 1.31427785],
       [1.76242647, 0.78498683, 0.57578388],
       [0.62868444, 0.0438871 , 1.65200415],
       [2.18918111, 1.62267317, 0.09498678],
       [0.5757371 , 0.10993565, 0.07281788]])

In [134]:
# 각 성분의 제곱근 계산하기 ( == array ** 0.5)
np.sqrt(arr1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[       nan,        nan, 1.14641958],
       [       nan, 0.88599483,        nan],
       [       nan,        nan, 1.28530314],
       [1.47958816,        nan, 0.30819926],
       [0.75877342,        nan,        nan]])

In [135]:
# 각 성분의 제곱 계산하기
np.square(arr1)

array([[2.95791022e-01, 2.50962126e-01, 1.72732627e+00],
       [3.10614708e+00, 6.16204325e-01, 3.31527073e-01],
       [3.95244128e-01, 1.92607774e-03, 2.72911773e+00],
       [4.79251394e+00, 2.63306820e+00, 9.02248920e-03],
       [3.31473211e-01, 1.20858470e-02, 5.30244378e-03]])

In [138]:
# 각 성분이 NaN인 경우 True를, 아닌 경우 False를 반환하기
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [139]:
# 전체 성분의 합을 계산
np.sum(arr1)

0.7501373109068715

In [140]:
# 열 간의 합을 계산
np.sum(arr1, axis=1)

array([ 0.26944992, -1.55322352,  0.97943261,  0.66149473,  0.39298357])

In [141]:
# 행 간의 합을 계산
np.sum(arr1, axis=0)

array([-0.17005943, -1.49247029,  2.41266703])

In [0]:
# 전체 성분의 표준편차, 분산, 최소값, 최대값 계산
# (std, var, min, max)


In [142]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환
# (argmin, argmax)

# NumPy는 축 인수를 추가하여 행과 열을 개별적으로 찾는다. 주어지지 않을 때, 배열은 단일 1D 배열로 평탄화된다.

np.argmin(arr1)


3

In [143]:
np.argmax(arr1)

9

In [146]:
# 맨 처음 성분부터 각 성분까지의 누적합 또는 누적곱을 계산
# (cumsum, cumprod)
print(arr1)
np.cumsum(arr1, axis=1)

[[-0.54386673 -0.5009612   1.31427785]
 [-1.76242647  0.78498683 -0.57578388]
 [-0.62868444 -0.0438871   1.65200415]
 [ 2.18918111 -1.62267317  0.09498678]
 [ 0.5757371  -0.10993565 -0.07281788]]


array([[-0.54386673, -1.04482793,  0.26944992],
       [-1.76242647, -0.97743964, -1.55322352],
       [-0.62868444, -0.67257154,  0.97943261],
       [ 2.18918111,  0.56650795,  0.66149473],
       [ 0.5757371 ,  0.46580145,  0.39298357]])

In [147]:
print(arr1)
np.cumsum(arr1, axis=0)

[[-0.54386673 -0.5009612   1.31427785]
 [-1.76242647  0.78498683 -0.57578388]
 [-0.62868444 -0.0438871   1.65200415]
 [ 2.18918111 -1.62267317  0.09498678]
 [ 0.5757371  -0.10993565 -0.07281788]]


array([[-0.54386673, -0.5009612 ,  1.31427785],
       [-2.30629321,  0.28402563,  0.73849397],
       [-2.93497765,  0.24013853,  2.39049813],
       [-0.74579654, -1.38253464,  2.48548491],
       [-0.17005943, -1.49247029,  2.41266703]])

In [148]:
print(arr1)
np.cumprod(arr1, axis=1)

[[-0.54386673 -0.5009612   1.31427785]
 [-1.76242647  0.78498683 -0.57578388]
 [-0.62868444 -0.0438871   1.65200415]
 [ 2.18918111 -1.62267317  0.09498678]
 [ 0.5757371  -0.10993565 -0.07281788]]


array([[-0.54386673,  0.27245613,  0.35808306],
       [-1.76242647, -1.38348157,  0.79658638],
       [-0.62868444,  0.02759114,  0.04558068],
       [ 2.18918111, -3.55232545, -0.33742397],
       [ 0.5757371 , -0.06329403,  0.00460894]])

In [150]:
print(arr1)
np.cumprod(arr1, axis=0)

[[-0.54386673 -0.5009612   1.31427785]
 [-1.76242647  0.78498683 -0.57578388]
 [-0.62868444 -0.0438871   1.65200415]
 [ 2.18918111 -1.62267317  0.09498678]
 [ 0.5757371  -0.10993565 -0.07281788]]


array([[-0.54386673, -0.5009612 ,  1.31427785],
       [ 0.95852513, -0.39324795, -0.75674   ],
       [-0.60260984,  0.01725851, -1.25013762],
       [-1.31922207, -0.02800493, -0.11874655],
       [-0.75952509,  0.00307874,  0.00864687]])

In [0]:
# 6-4. 기타 함수

In [152]:
# 같은 행에 대해서 오름차순으로 정렬
np.sort(arr1, axis=0)

array([[-1.76242647, -1.62267317, -0.57578388],
       [-0.62868444, -0.5009612 , -0.07281788],
       [-0.54386673, -0.10993565,  0.09498678],
       [ 0.5757371 , -0.0438871 ,  1.31427785],
       [ 2.18918111,  0.78498683,  1.65200415]])

In [153]:
# 같은 행에 대해서 내림차순으로 정렬
np.sort(arr1, axis=0)[::-1]

array([[ 2.18918111,  0.78498683,  1.65200415],
       [ 0.5757371 , -0.0438871 ,  1.31427785],
       [-0.54386673, -0.10993565,  0.09498678],
       [-0.62868444, -0.5009612 , -0.07281788],
       [-1.76242647, -1.62267317, -0.57578388]])